title: 川崎Ruby会議01
description: kawasaki.rb主催の地域Ruby会議「川崎Ruby会議01」の情報を掲載しています
baseurl: "/kwsk01"
url: "http://regional.rubykaigi.org"
twitter_username: kawasakirb
github_username:  kawasakirb
encoding: UTF-8

# Build settings
markdown: kramdown
